/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kmajanlatkeresadmin;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lia
 */
public class KMAjanlatkeresAdmin extends javax.swing.JFrame {

    String DBUrl = "jdbc:mysql://localhost/kmajanlatkeres";
    String DBNev = "root";
    String DBJelszo = "";

    /**
     * Creates new form KMAjanlatkeresAdmin
     */
    public KMAjanlatkeresAdmin() {
        initComponents();
        menu.setVisible(false);
        ajanlatFrame.setVisible(false);
        munkaFrame.setVisible(false);

        this.loadAjanlatok();
        this.loadMunkak();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bejelentkezesFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBejelentkezes = new javax.swing.JButton();
        tfNev = new javax.swing.JTextField();
        pfJelszo = new javax.swing.JPasswordField();
        ajanlatFrame = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAjanlatok = new javax.swing.JTable();
        btnTorol = new javax.swing.JButton();
        btnElfogad = new javax.swing.JButton();
        btnTeljesitve = new javax.swing.JButton();
        munkaFrame = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMunkak = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfMunka = new javax.swing.JTextField();
        btnMunka = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        mAjanlat = new javax.swing.JMenu();
        mMunka = new javax.swing.JMenu();
        mKilepes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bejelentkezesFrame.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Bejelentkezés");

        jLabel2.setText("Név:");

        jLabel3.setText("Jelszó:");

        btnBejelentkezes.setText("Bejelentkezés");
        btnBejelentkezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBejelentkezesActionPerformed(evt);
            }
        });

        tfNev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bejelentkezesFrameLayout = new javax.swing.GroupLayout(bejelentkezesFrame.getContentPane());
        bejelentkezesFrame.getContentPane().setLayout(bejelentkezesFrameLayout);
        bejelentkezesFrameLayout.setHorizontalGroup(
            bejelentkezesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bejelentkezesFrameLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(195, 195, 195))
            .addGroup(bejelentkezesFrameLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(bejelentkezesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bejelentkezesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBejelentkezes, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(bejelentkezesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfNev, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(pfJelszo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bejelentkezesFrameLayout.setVerticalGroup(
            bejelentkezesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bejelentkezesFrameLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(bejelentkezesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(bejelentkezesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pfJelszo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnBejelentkezes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        ajanlatFrame.setVisible(true);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Ajánlatok");

        tbAjanlatok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Név", "Telefon", "Munka", "Négyzetméter", "Állapot"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAjanlatok);

        btnTorol.setText("Törlés");
        btnTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorolActionPerformed(evt);
            }
        });

        btnElfogad.setText("Elfogad");
        btnElfogad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElfogadActionPerformed(evt);
            }
        });

        btnTeljesitve.setText("Teljesítve");
        btnTeljesitve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeljesitveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajanlatFrameLayout = new javax.swing.GroupLayout(ajanlatFrame.getContentPane());
        ajanlatFrame.getContentPane().setLayout(ajanlatFrameLayout);
        ajanlatFrameLayout.setHorizontalGroup(
            ajanlatFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajanlatFrameLayout.createSequentialGroup()
                .addGroup(ajanlatFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajanlatFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                    .addGroup(ajanlatFrameLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ajanlatFrameLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnTorol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnElfogad)
                .addGap(109, 109, 109)
                .addComponent(btnTeljesitve)
                .addGap(41, 41, 41))
        );
        ajanlatFrameLayout.setVerticalGroup(
            ajanlatFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajanlatFrameLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ajanlatFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTorol)
                    .addComponent(btnElfogad)
                    .addComponent(btnTeljesitve))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        munkaFrame.setVisible(true);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Munkák");

        tbMunkak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Munka"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbMunkak);

        jLabel6.setText("Új:");

        jLabel7.setText("Munka:");

        btnMunka.setText("Hozzáadás");
        btnMunka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunkaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout munkaFrameLayout = new javax.swing.GroupLayout(munkaFrame.getContentPane());
        munkaFrame.getContentPane().setLayout(munkaFrameLayout);
        munkaFrameLayout.setHorizontalGroup(
            munkaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, munkaFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(223, 223, 223))
            .addGroup(munkaFrameLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(munkaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(munkaFrameLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6))
                    .addGroup(munkaFrameLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(munkaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMunka, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(munkaFrameLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(tfMunka, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        munkaFrameLayout.setVerticalGroup(
            munkaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(munkaFrameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGroup(munkaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(munkaFrameLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(munkaFrameLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(munkaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfMunka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btnMunka, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        mAjanlat.setText("Ajánlatok");
        mAjanlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mAjanlatMousePressed(evt);
            }
        });
        menu.add(mAjanlat);

        mMunka.setText("Munkák");
        mMunka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mMunkaMousePressed(evt);
            }
        });
        menu.add(mMunka);

        mKilepes.setText("Kilépés");
        mKilepes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mKilepesMousePressed(evt);
            }
        });
        menu.add(mKilepes);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bejelentkezesFrame)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ajanlatFrame))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(munkaFrame))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bejelentkezesFrame)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ajanlatFrame))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(munkaFrame))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mKilepesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mKilepesMousePressed
        System.exit(0);
    }//GEN-LAST:event_mKilepesMousePressed

    private void tfNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNevActionPerformed

    private void btnBejelentkezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBejelentkezesActionPerformed
        String nev = tfNev.getText();
        String jelszo = pfJelszo.getText();

        MessageDigest m;
        try {
            m = MessageDigest.getInstance("MD5");
            m.update(jelszo.getBytes(), 0, jelszo.length());
            jelszo = new BigInteger(1, m.digest()).toString(16);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = (Connection) DriverManager.getConnection(DBUrl, DBNev, DBJelszo);
            Statement stmt = (Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM felhasznalok WHERE felh_nev='" + nev + "'");

            if (rs.next() && jelszo.equals(rs.getString("jelszo"))) {
                menu.setVisible(true);
                ajanlatFrame.setVisible(true);
                bejelentkezesFrame.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Hibás felhasználónév vagy jelszó!", "Hiba!", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnBejelentkezesActionPerformed

    private void btnElfogadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElfogadActionPerformed
        int selected = tbAjanlatok.getSelectedRow();
        String id = tbAjanlatok.getValueAt(selected, 0).toString();

        try {
            Connection con = (Connection) DriverManager.getConnection(DBUrl, DBNev, DBJelszo);
            Statement stmt = (Statement) con.createStatement();
            stmt.executeUpdate("UPDATE ajanlatok SET allapot='elfogadva' WHERE id=" + id);
            
            loadAjanlatok();
        } catch (SQLException ex) {
            Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnElfogadActionPerformed

    private void btnTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorolActionPerformed
        int selected = tbAjanlatok.getSelectedRow();
        String id = tbAjanlatok.getValueAt(selected, 0).toString();

        try {
            Connection con = (Connection) DriverManager.getConnection(DBUrl, DBNev, DBJelszo);
            Statement stmt = (Statement) con.createStatement();
            stmt.executeUpdate("DELETE FROM ajanlatok WHERE id=" + id);
            
            loadAjanlatok();
        } catch (SQLException ex) {
            Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnTorolActionPerformed

    private void btnTeljesitveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeljesitveActionPerformed
        int selected = tbAjanlatok.getSelectedRow();
        String id = tbAjanlatok.getValueAt(selected, 0).toString();

        try {
            Connection con = (Connection) DriverManager.getConnection(DBUrl, DBNev, DBJelszo);
            Statement stmt = (Statement) con.createStatement();
            stmt.executeUpdate("UPDATE ajanlatok SET allapot='teljesítve' WHERE id=" + id);
            
            loadAjanlatok();
        } catch (SQLException ex) {
            Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTeljesitveActionPerformed

    private void btnMunkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunkaActionPerformed
        String munka = tfMunka.getText();

        try {
            Connection con = (Connection) DriverManager.getConnection(DBUrl, DBNev, DBJelszo);
            Statement stmt = (Statement) con.createStatement();
            stmt.executeUpdate("INSERT INTO munkak VALUES(NULL, '" + munka + "')");
            
            loadMunkak();
        } catch (SQLException ex) {
            Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMunkaActionPerformed

    private void mAjanlatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mAjanlatMousePressed
        ajanlatFrame.setVisible(true);
        munkaFrame.setVisible(false);
    }//GEN-LAST:event_mAjanlatMousePressed

    private void mMunkaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMunkaMousePressed
        ajanlatFrame.setVisible(false);
        munkaFrame.setVisible(true);
    }//GEN-LAST:event_mMunkaMousePressed

    public void loadAjanlatok() {
        try {
            Connection con = (Connection) DriverManager.getConnection(DBUrl, DBNev, DBJelszo);
            Statement stmt = (Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT ajanlatok.*, munkak.munka AS munk FROM ajanlatok JOIN munkak ON munkak.id=ajanlatok.munka_id");

            ((DefaultTableModel) tbAjanlatok.getModel()).setRowCount(0);
            while (rs.next()) {
                ((DefaultTableModel) tbAjanlatok.getModel()).addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nev"),
                    rs.getString("tel"),
                    rs.getString("munk"),
                    rs.getInt("m"),
                    rs.getString("allapot")
                });
            }

        } catch (SQLException ex) {
            Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void loadMunkak() {
        try {
            Connection con = (Connection) DriverManager.getConnection(DBUrl, DBNev, DBJelszo);
            Statement stmt = (Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM munkak");

            ((DefaultTableModel) tbMunkak.getModel()).setRowCount(0);
            while (rs.next()) {
                ((DefaultTableModel) tbMunkak.getModel()).addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("munka")
                });
            }

        } catch (SQLException ex) {
            Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KMAjanlatkeresAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KMAjanlatkeresAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame ajanlatFrame;
    private javax.swing.JInternalFrame bejelentkezesFrame;
    private javax.swing.JButton btnBejelentkezes;
    private javax.swing.JButton btnElfogad;
    private javax.swing.JButton btnMunka;
    private javax.swing.JButton btnTeljesitve;
    private javax.swing.JButton btnTorol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu mAjanlat;
    private javax.swing.JMenu mKilepes;
    private javax.swing.JMenu mMunka;
    private javax.swing.JMenuBar menu;
    private javax.swing.JInternalFrame munkaFrame;
    private javax.swing.JPasswordField pfJelszo;
    private javax.swing.JTable tbAjanlatok;
    private javax.swing.JTable tbMunkak;
    private javax.swing.JTextField tfMunka;
    private javax.swing.JTextField tfNev;
    // End of variables declaration//GEN-END:variables
}
